### ISSUE TITLE
Bug in library inclusion

### ISSUE THREAD

**Issue by wkoprek** [paulscherrerinstitute/TbGenerator#2]
Even when the library in the source file is commented out like this
library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

, the scripts generating the tb file creates the inclusion

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

**Comment by obruendl** [comment]
A bugfix is implemented
